# 服务器运行配置项
server:
  port: 9000
  jwt:
    tokenHead: 'Bearer '
    tokenHeader: Authorization
    key: HORL)JUZ&AFIW*(XGS
    expiration: 86400
# mysql配置项
mysql:
  host: localhost
  port: 3306
  user: root
  password: shotrise
  name: mall
  charset: utf8mb4
  loc: Asia/Shanghai
  time: 10
  maxOpenConns: 20
  maxIdelConns: 2


log:
  path: ./out/logout
  level: debug

Redis:
  host: localhost:6379
  password:
  db: 0
  dialTimeout: 10
  readTimeout: 30
  writeTimeout: 30
  poolSize: 10
  poolTimeout: 30
  database: mall
  key:
    orderId: 'ums:authCode'
    member: 'oms:orderId'
    authCode: 'ums:authCode'
  expire:
    authCode: 60
    common: 86400 # 24小时

elasticsearch:
  repositories:
    enabled: true
  clusterNodes: 127.0.0.1:9200 # es的连接地址及端口号
  clusterName: elasticsearch # es集群的名称

mongodb:
  credential:
    authMechanism:
    authSource:
    username:
    password:
  timeout: 10
  maxPoolSize: 10
  minPoolSize: 2
  host:
    - localhost:2701
  database: mall-port

