// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/18211167516/Go-Gin-Api",
        "contact": {
            "name": "meme",
            "email": "962349367@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/brand/create": {
            "post": {
                "description": "创建一个品牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "品牌接口"
                ],
                "summary": "创建品牌",
                "operationId": "v1/PmsBrandController/createBrand",
                "parameters": [
                    {
                        "description": "pmsBrand",
                        "name": "pmsBrand",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PmsBrand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PmsBrand"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PmsBrand"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/brand/delete/{id}": {
            "get": {
                "description": "删除品牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "品牌接口"
                ],
                "summary": "删除品牌",
                "operationId": "v1/PmsBrandController/deleteBrand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "brand_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/brand/list": {
            "get": {
                "description": "获取品牌列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "品牌接口"
                ],
                "summary": "获取品牌列表",
                "operationId": "v1/PmsBrandController/list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PmsBrand"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/brand/update/{id}": {
            "post": {
                "description": "更新品牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "品牌接口"
                ],
                "summary": "更新品牌",
                "operationId": "v1/PmsBrandController/updateBrand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "brand_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "pmsBrand",
                        "name": "pmsBrand",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PmsBrand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PmsBrand"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/brand/{id}": {
            "get": {
                "description": "获取一个品牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "品牌接口"
                ],
                "summary": "获取一个品牌",
                "operationId": "v1/PmsBrandController/brand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "brand_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PmsBrand"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/create/{id}": {
            "post": {
                "description": "根据id创建商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "根据id创建商品",
                "operationId": "v1/esProduct/Create",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "product_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/document.EsProduct"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/delete/batch": {
            "post": {
                "description": "根据id批量删除商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "根据id批量删除商品",
                "operationId": "v1/esProduct/DeleteBatch",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "description": "product_ids",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/delete/{id}": {
            "get": {
                "description": "根据id删除商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "根据id删除商品",
                "operationId": "v1/esProduct/Delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "product_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/esProduct/importAll": {
            "get": {
                "description": "导入所有数据库中商品到ES",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "导入所有数据库中商品到ES",
                "operationId": "v1/esProduct/importAll",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/recommend/{id}": {
            "get": {
                "description": "根据商品id推荐商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "根据商品id推荐商品",
                "operationId": "v1/esProduct/Recommend",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "brandId",
                        "name": "brandId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "综合搜索、筛选、排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "综合搜索、筛选、排序",
                "operationId": "v1/esProduct/SearchDetail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "brandId",
                        "name": "brandId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "productCategoryId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "sort 排序字段:0-\u003e按相关度；1-\u003e按新品；2-\u003e按销量；3-\u003e价格从低到高；4-\u003e价格从高到低",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/search/relate": {
            "get": {
                "description": "获取搜索的相关品牌、分类及筛选属性",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "获取搜索的相关品牌、分类及筛选属性",
                "operationId": "v1/esProduct/SearchRelatedInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.EsProductRelatedInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/search/simple": {
            "get": {
                "description": "简单搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索商品管理"
                ],
                "summary": "简单搜索",
                "operationId": "v1/esProduct/SearchSimple",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseMsg"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/document.EsProduct"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/sso/getAuthCode": {
            "get": {
                "description": "获取验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "获取验证码",
                "operationId": "v1/UmsMemberController/GetAuthCode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "telephone",
                        "name": "telephone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/sso/verifyAuthCode": {
            "post": {
                "description": "确认验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "确认验证码",
                "operationId": "v1/UmsMemberController/UpdatePassword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "telephone",
                        "name": "telephone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authcode",
                        "name": "authcode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    },
                    "500": {
                        "description": "failure",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "document.EsProduct": {
            "type": "object",
            "properties": {
                "album_pics": {
                    "description": "是否可空:YES 画册图片，连产品图片限制为5张，以逗号分割",
                    "type": "string"
                },
                "attrValueList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.EsProductAttributeValue"
                    }
                },
                "brand_id": {
                    "description": "是否可空:YES",
                    "type": "integer"
                },
                "brand_name": {
                    "description": "是否可空:YES 品牌名称",
                    "type": "string"
                },
                "delete_status": {
                    "description": "是否可空:YES 删除状态：0-\u003e未删除；1-\u003e已删除",
                    "type": "integer"
                },
                "description": {
                    "description": "是否可空:YES 商品描述",
                    "type": "string"
                },
                "detail_desc": {
                    "description": "是否可空:YES",
                    "type": "string"
                },
                "detail_html": {
                    "description": "是否可空:YES 产品详情网页内容",
                    "type": "string"
                },
                "detail_mobile_html": {
                    "description": "是否可空:YES 移动端网页详情",
                    "type": "string"
                },
                "detail_title": {
                    "description": "是否可空:YES",
                    "type": "string"
                },
                "feight_template_id": {
                    "description": "是否可空:YES",
                    "type": "integer"
                },
                "gift_growth": {
                    "description": "是否可空:YES 赠送的成长值",
                    "type": "integer"
                },
                "gift_point": {
                    "description": "是否可空:YES 赠送的积分",
                    "type": "integer"
                },
                "id": {
                    "description": "是否可空:NO",
                    "type": "integer"
                },
                "keywords": {
                    "description": "是否可空:YES",
                    "type": "string"
                },
                "low_stock": {
                    "description": "是否可空:YES 库存预警值",
                    "type": "integer"
                },
                "name": {
                    "description": "是否可空:NO",
                    "type": "string"
                },
                "new_status": {
                    "description": "是否可空:YES 新品状态:0-\u003e不是新品；1-\u003e新品",
                    "type": "integer"
                },
                "note": {
                    "description": "是否可空:YES",
                    "type": "string"
                },
                "original_price": {
                    "description": "是否可空:YES 市场价",
                    "type": "number"
                },
                "pic": {
                    "description": "是否可空:YES",
                    "type": "string"
                },
                "preview_status": {
                    "description": "是否可空:YES 是否为预告商品：0-\u003e不是；1-\u003e是",
                    "type": "integer"
                },
                "price": {
                    "description": "是否可空:YES",
                    "type": "number"
                },
                "product_attribute_category_id": {
                    "description": "是否可空:YES",
                    "type": "integer"
                },
                "product_category_id": {
                    "description": "是否可空:YES",
                    "type": "integer"
                },
                "product_category_name": {
                    "description": "是否可空:YES 商品分类名称",
                    "type": "string"
                },
                "product_sn": {
                    "description": "是否可空:NO 货号",
                    "type": "string"
                },
                "promotion_end_time": {
                    "description": "是否可空:YES 促销结束时间",
                    "type": "string"
                },
                "promotion_per_limit": {
                    "description": "是否可空:YES 活动限购数量",
                    "type": "integer"
                },
                "promotion_price": {
                    "description": "是否可空:YES 促销价格",
                    "type": "number"
                },
                "promotion_start_time": {
                    "description": "是否可空:YES 促销开始时间",
                    "type": "string"
                },
                "promotion_type": {
                    "description": "是否可空:YES 促销类型：0-\u003e没有促销使用原价;1-\u003e使用促销价；2-\u003e使用会员价；3-\u003e使用阶梯价格；4-\u003e使用满减价格；5-\u003e限时购",
                    "type": "integer"
                },
                "publish_status": {
                    "description": "是否可空:YES 上架状态：0-\u003e下架；1-\u003e上架",
                    "type": "integer"
                },
                "recommand_status": {
                    "description": "是否可空:YES 推荐状态；0-\u003e不推荐；1-\u003e推荐",
                    "type": "integer"
                },
                "sale": {
                    "description": "是否可空:YES 销量",
                    "type": "integer"
                },
                "service_ids": {
                    "description": "是否可空:YES 以逗号分割的产品服务：1-\u003e无忧退货；2-\u003e快速退款；3-\u003e免费包邮",
                    "type": "string"
                },
                "sort": {
                    "description": "是否可空:YES 排序",
                    "type": "integer"
                },
                "stock": {
                    "description": "是否可空:YES 库存",
                    "type": "integer"
                },
                "sub_title": {
                    "description": "是否可空:YES 副标题",
                    "type": "string"
                },
                "unit": {
                    "description": "是否可空:YES 单位",
                    "type": "string"
                },
                "use_point_limit": {
                    "description": "是否可空:YES 限制使用的积分数",
                    "type": "integer"
                },
                "verify_status": {
                    "description": "是否可空:YES 审核状态：0-\u003e未审核；1-\u003e审核通过",
                    "type": "integer"
                },
                "weight": {
                    "description": "是否可空:YES 商品重量，默认为克",
                    "type": "number"
                }
            }
        },
        "domain.EsProductAttributeValue": {
            "type": "object",
            "properties": {
                "attr_id": {
                    "type": "integer"
                },
                "attr_name": {
                    "type": "string"
                },
                "attr_product_attribute_id": {
                    "type": "integer"
                },
                "attr_type": {
                    "type": "string"
                },
                "attr_value": {
                    "type": "string"
                }
            }
        },
        "domain.EsProductRelatedInfo": {
            "type": "object",
            "properties": {
                "brandNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "productAttrs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductAttr"
                    }
                },
                "productCategoryNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.ProductAttr": {
            "type": "object",
            "properties": {
                "attrId": {
                    "type": "integer"
                },
                "attrName": {
                    "type": "string"
                },
                "attrValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.PmsBrand": {
            "type": "object",
            "properties": {
                "big_pic": {
                    "description": "是否可空:YES 专区大图",
                    "type": "string"
                },
                "brand_story": {
                    "description": "是否可空:YES 品牌故事",
                    "type": "string"
                },
                "factory_status": {
                    "description": "是否可空:YES 是否为品牌制造商：0-\u003e不是；1-\u003e是",
                    "type": "integer"
                },
                "first_letter": {
                    "description": "是否可空:YES 首字母",
                    "type": "string"
                },
                "id": {
                    "description": "是否可空:NO",
                    "type": "integer"
                },
                "logo": {
                    "description": "是否可空:YES 品牌logo",
                    "type": "string"
                },
                "name": {
                    "description": "是否可空:YES",
                    "type": "string"
                },
                "product_comment_count": {
                    "description": "是否可空:YES 产品评论数量",
                    "type": "integer"
                },
                "product_count": {
                    "description": "是否可空:YES 产品数量",
                    "type": "integer"
                },
                "show_status": {
                    "description": "是否可空:YES",
                    "type": "integer"
                },
                "sort": {
                    "description": "是否可空:YES",
                    "type": "integer"
                }
            }
        },
        "response.ResponseMsg": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "mall",
	Description:      "mall",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
